### ISSUE TITLE
Start-up crash

### ISSUE THREAD

**Issue by Beanius** [oneandonlyflexo/botaunomy#1]
https://gist.github.com/anonymous/bc3ffdc4666046651debd412c75a46cd

**Comment by Alaberti** [comment]
I also have this crash, using Botania r1.10-350 and forge 14.23.0.2544.

**Comment by Kevun1** [comment]
Also present forge v2545. Even with just Botania + Botaunomy, it crashes on startup. The mod is currently unplayable (literally).

**Comment by oneandonlyflexo** [comment]
Yup. I'm aware. It works in the dev environment. There's something I'm doing wrong with the way I'm building the mod. Hopefully I'll have time this weekend to look into it.

Thanks everyone for the crashlogs!

**Comment by Alaberti** [comment]
Has there been any update on this? Really looking forward to adding this to my pack!

**Comment by oneandonlyflexo** [comment]
I had a bit of time to try and look into, unfortunately I'm not really sure what could be the problem with the build I submitted.  I spent some time working on a tiny other mod and working on a shared code mod to aid in mod dev for myself.  Those projects are looking in a good place so now I'm hoping to jump back into botaunomy.  Sorry for the delay guys!

**Comment by oneandonlyflexo** [comment]
This should finally be resolved with commit 17fba5f.  Probably a mod load order thing.  Either that or not using SideOnly annotations in all the right spots.
