### ISSUE TITLE
[0.2] Crash on game startup

### ISSUE THREAD

**Issue by Alaberti** [oneandonlyflexo/botaunomy#2]
https://pastebin.com/0c9xcJgG

"java.lang.NoSuchMethodError: one.flexo.botaunomy.block.ElvenAvatarBlock.registerCustomItemblock(Lone/flexo/nibbler/block/NibblerBlock;)V"

Help?

**Comment by Alaberti** [comment]
Using nibbler-1.12.2-0.3.jar as well.

**Comment by oneandonlyflexo** [comment]
Gah! Really? That is very strange. I tested in a fresh install in multimc separate from my dev environment and everything.... should be able to take a look tonight.

**Comment by oneandonlyflexo** [comment]
Ah I figured it out!  I updated Nibbler with the change that botaunomy required.  I'll just revert Botaunomy to not need that update when I get home.
